import { execSync } from "child_process";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const root = path.resolve(__dirname, "..", "..", "..");

const GENERATED_DIRS = [
  path.resolve(root, "lib", "api-client-react", "src", "generated"),
  path.resolve(root, "lib", "api-zod", "src", "generated"),
];

const BACKUP_SUFFIX = "__safe_codegen_backup__";
const API_ZOD_GENERATED_DIR = path.resolve(
  root,
  "lib",
  "api-zod",
  "src",
  "generated",
);
const PUBLIC_BARREL_FILES = [
  path.resolve(root, "lib", "api-client-react", "src", "index.ts"),
  path.resolve(root, "lib", "api-zod", "src", "index.ts"),
];
const publicBarrelContents = new Map(
  PUBLIC_BARREL_FILES.map((file) => [file, fs.readFileSync(file, "utf8")]),
);

function backup(dir) {
  const backupDir = dir + BACKUP_SUFFIX;
  if (fs.existsSync(backupDir)) {
    fs.rmSync(backupDir, { recursive: true, force: true });
  }
  if (fs.existsSync(dir)) {
    fs.cpSync(dir, backupDir, { recursive: true });
  }
}

function restore(dir) {
  const backupDir = dir + BACKUP_SUFFIX;
  if (fs.existsSync(backupDir)) {
    if (fs.existsSync(dir)) {
      fs.rmSync(dir, { recursive: true, force: true });
    }
    fs.renameSync(backupDir, dir);
  }
}

function dropBackup(dir) {
  const backupDir = dir + BACKUP_SUFFIX;
  if (fs.existsSync(backupDir)) {
    fs.rmSync(backupDir, { recursive: true, force: true });
  }
}

function dropGenerated(dir) {
  if (fs.existsSync(dir)) {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function writeApiZodPublicBarrel() {
  const typesDir = path.join(API_ZOD_GENERATED_DIR, "types");
  const apiSource = fs.readFileSync(
    path.join(API_ZOD_GENERATED_DIR, "api.ts"),
    "utf8",
  );
  const apiValueNames = new Set(
    [
      ...apiSource.matchAll(
        /^export (?:const|let|var|function|class|enum) ([A-Za-z_$][\w$]*)/gm,
      ),
    ].map((match) => match[1]),
  );
  const typeFiles = fs
    .readdirSync(typesDir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith(".ts") && entry.name !== "index.ts")
    .map((entry) => entry.name)
    .sort();

  const typeExports = [];

  for (const fileName of typeFiles) {
    const source = fs.readFileSync(path.join(typesDir, fileName), "utf8");
    const exportedTypeNames = [
      ...source.matchAll(/^export (?:interface|type) ([A-Za-z_$][\w$]*)/gm),
    ]
      .map((match) => match[1])
      .filter((name) => !apiValueNames.has(name))
      .sort();

    if (exportedTypeNames.length === 0) {
      continue;
    }

    const moduleName = fileName.slice(0, -".ts".length);
    typeExports.push(
      `export type { ${exportedTypeNames.join(", ")} } from "./types/${moduleName}";`,
    );
  }

  const contents = `/**
 * Generated by the API spec codegen wrapper.
 * Do not edit manually.
 *
 * Zod schemas are runtime values. Generated OpenAPI models are re-exported
 * explicitly as types when they do not collide with a schema value. Runtime
 * schemas keep their existing public names without ambiguous star exports.
 */
export * from "./api";
${typeExports.join("\n")}
`;

  fs.writeFileSync(path.join(API_ZOD_GENERATED_DIR, "index.ts"), contents);
}

function restorePublicBarrels() {
  for (const [file, contents] of publicBarrelContents) {
    fs.writeFileSync(file, contents);
  }
}

function preserveOptionalTransitionBodies() {
  const apiPath = path.resolve(
    root,
    "lib",
    "api-client-react",
    "src",
    "generated",
    "api.ts",
  );
  let source = fs.readFileSync(apiPath, "utf8");
  // Orval currently makes mutation variables required even when an OpenAPI
  // requestBody is optional. These two transitions intentionally support the
  // legacy body-less call, so keep `data` optional in the generated hooks.
  source = source.replace(
    /\{ id: string; data: BodyType<ThoughtArticleTransitionBody> \}/g,
    "{ id: string; data?: BodyType<ThoughtArticleTransitionBody> }",
  );
  fs.writeFileSync(apiPath, source);
}

function enforceIntegerCreateRetryGeneration() {
  const apiPath = path.join(API_ZOD_GENERATED_DIR, "api.ts");
  let source = fs.readFileSync(apiPath, "utf8");
  const before = `requestGeneration: zod
    .number()
    .min(1)`;
  const after = `requestGeneration: zod
    .number()
    .int()
    .min(1)`;
  if (!source.includes(before)) {
    throw new Error(
      "Generated CreateThoughtBody.requestGeneration schema was not found",
    );
  }
  source = source.replace(before, after);
  fs.writeFileSync(apiPath, source);
}

for (const dir of GENERATED_DIRS) {
  backup(dir);
  dropGenerated(dir);
}

try {
  execSync("orval --config ./orval.config.ts", {
    stdio: "inherit",
    cwd: path.resolve(__dirname, ".."),
  });

  writeApiZodPublicBarrel();
  restorePublicBarrels();

  for (const dir of GENERATED_DIRS) {
    dropBackup(dir);
  }
  preserveOptionalTransitionBodies();
  enforceIntegerCreateRetryGeneration();

  console.log("\n✓ Codegen succeeded. Generated files updated.");
} catch (err) {
  console.error("\n✗ Codegen failed. Restoring previous generated files...");

  for (const dir of GENERATED_DIRS) {
    dropGenerated(dir);
    restore(dir);
  }
  restorePublicBarrels();

  process.exit(1);
}
