// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/envelope-inbox/EnvelopeInbox.tsx": () => import("../components/mockups/envelope-inbox/EnvelopeInbox.tsx"),
  "./components/mockups/envelope-inbox/SealedEnvelopeInbox.tsx": () => import("../components/mockups/envelope-inbox/SealedEnvelopeInbox.tsx"),
  "./components/mockups/friction-navbar/FrictionNavBar.tsx": () => import("../components/mockups/friction-navbar/FrictionNavBar.tsx"),
  "./components/mockups/question-block/QuestionBlockPreview.tsx": () => import("../components/mockups/question-block/QuestionBlockPreview.tsx"),
  "./components/mockups/question-block-popup/QuestionBlockPopupPreview.tsx": () => import("../components/mockups/question-block-popup/QuestionBlockPopupPreview.tsx"),
  "./components/mockups/question-card-swipe/QuestionCardSwipePreview.tsx": () => import("../components/mockups/question-card-swipe/QuestionCardSwipePreview.tsx"),
  "./components/mockups/reader-swipe-next/ReaderSwipeNextPreview.tsx": () => import("../components/mockups/reader-swipe-next/ReaderSwipeNextPreview.tsx"),
  "./components/mockups/reading-complete/ReadingCompletePreview.tsx": () => import("../components/mockups/reading-complete/ReadingCompletePreview.tsx"),
  "./components/mockups/templates/MissionControlBentoDashboard-kWBE4B/Dashboard.tsx": () => import("../components/mockups/templates/MissionControlBentoDashboard-kWBE4B/Dashboard.tsx"),
  "./components/mockups/templates/SwissGridCRMDashboard-S8kGXy/App.tsx": () => import("../components/mockups/templates/SwissGridCRMDashboard-S8kGXy/App.tsx")
};
