// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/friction-navbar/FrictionNavBar.tsx": () => import("../components/mockups/friction-navbar/FrictionNavBar.tsx"),
  "./components/mockups/envelope-inbox/EnvelopeInbox.tsx": () => import("../components/mockups/envelope-inbox/EnvelopeInbox.tsx"),
  "./components/mockups/envelope-inbox/SealedEnvelopeInbox.tsx": () => import("../components/mockups/envelope-inbox/SealedEnvelopeInbox.tsx")
};
